version: '3.4'

services:
 sql-server:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'testInstancePassword'
    ports:
      - 1433:1433

 examplewebapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080"

  usingcontrollers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
